language: php

php:
  - 7.1

before_script:
  - composer validate
  - composer require silverstripe/installer:^4.0 --no-update
  - composer install --prefer-dist

script:
  - vendor/phpunit/phpunit/phpunit