---
Name: SilverStripe-PWA
---

SilverStripe\Control\Director:
  rules:
    'manifest.json': 'SilverStripePWA\Controllers\ManifestController'
    'service-worker.js': 'SilverStripePWA\Controllers\ServiceWorkerController'
    'RegisterServiceWorker.js': 'SilverStripePWA\Controllers\RegisterServiceWorkerController'
    'offline.html': 'SilverStripePWA\Controllers\OfflinePageController'
    'push': 'SilverStripePWA\Controllers\SendPushNotificationController'
    'RegisterSubscription': 'SilverStripePWA\Controllers\RegisterSubscriptionController'

SilverStripe\SiteConfig\SiteConfig:
    extensions:
        - SilverStripePWA\Extensions\ManifestSiteConfigExtension
        - SilverStripePWA\Extensions\PushNotificationsSiteConfigExtension

# Add the push-extension to the page of your choosing

# Example\Example\ArticlePage:
#     extensions:
#         - SilverStripePWA\Extensions\PushArticleExtension