---
Name: SilverStripe-PWA
---

SilverStripe\Control\Director:
  rules:
    'manifest.json': 'SilverStripePWA\Controllers\ManifestController'
    'service-worker.js': 'SilverStripePWA\Controllers\ServiceWorkerController'
    'notifications.js': 'SilverStripePWA\Controllers\NotificationController'
    'offline.html': 'SilverStripePWA\Controllers\OfflineController'
    'push': 'SilverStripePWA\Controllers\PushNotificationController'
    'add_subscription': 'SilverStripePWA\Controllers\SubscriptionController'

SilverStripe\SiteConfig\SiteConfig:
    extensions:
        - SilverStripePWA\Extensions\ManifestSiteConfigExtension
        - SilverStripePWA\Extensions\PushNotificationsSiteConfigExtension

# SilverStripe\Lessons\ArticlePage:
#     extensions:
#         - SilverStripePWA\Extensions\PushArticleExtension